client_id: ABCDEFGHIJK
client_secret: ASDFGHKL
identity_provider_id: LMNOPQRTSUV
identity_pool_id: WXYZ0123456789
console_destination: https://console.awscreds.amazon.com/cloudwatch
console_issuer: example.com
